<a href="https://colab.research.google.com/github/sam002696/pytorch_colab/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


## Intro to Tensors

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
TENSOR = torch.tensor([[[1,2,3],
                       [5,8,9],
                       [9,8,1]]])
TENSOR

tensor([[[1, 2, 3],
         [5, 8, 9],
         [9, 8, 1]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
MAT_DIMENSION = torch.tensor([[[[[1,7,9],
                               [7,8,2],
                               [6,1,2]
                                 ]]]])
MAT_DIMENSION

tensor([[[[[1, 7, 9],
           [7, 8, 2],
           [6, 1, 2]]]]])

In [ ]:
MAT_DIMENSION.ndim , MAT_DIMENSION.shape , MAT_DIMENSION[0]

(5,
 torch.Size([1, 1, 1, 3, 3]),
 tensor([[[[1, 7, 9],
           [7, 8, 2],
           [6, 1, 2]]]]))

**Scalar**

In [ ]:
scalar = torch.tensor(7)
scalar, scalar.ndim, scalar.shape

(tensor(7), 0, torch.Size([]))

**Vectors**

In [ ]:
vector = torch.tensor([7,6])
vector , vector.ndim , vector.shape

(tensor([7, 6]), 1, torch.Size([2]))

**Random Tensors**



In [ ]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8698, 0.6722, 0.5841, 0.5290],
        [0.7722, 0.4655, 0.4110, 0.6027],
        [0.9388, 0.8686, 0.3164, 0.7293]])

`Image Tensors`

In [ ]:
# Creating a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
zeros_tensor = torch.zeros(size=[3,4])
ones_tensor = torch.ones(size=[1,3,4])


zeros_tensor, ones_tensor, zeros_tensor.dtype, ones_tensor.dtype
# zeros_tensor * ones_tensor


(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]),
 torch.float32,
 torch.float32)

In [ ]:
zeros_tensor * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
tensor1 = torch.tensor([1,4,5])
tensor2 = torch.tensor([9,6,3])

print(torch.matmul(tensor1, tensor2))

tensor(48)


In [ ]:
tensor_mat1 = torch.rand([3,2])
tensor_mat2 = torch.rand([2,3])
torch.mm(tensor_mat1 , tensor_mat2)

tensor([[0.2179, 0.2404, 0.4312],
        [0.7107, 0.5958, 0.8547],
        [0.7154, 0.5288, 0.6521]])

In [ ]:
print("hello")